# Generated by Django 5.1.15 on 2026-09-22 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Resource Created'), ('UPDATE', 'Resource Updated'), ('DELETE', 'Resource Deleted'), ('ROLE_CHANGE', 'User Role Changed'), ('PAYROLL_ACCESS', 'Payroll Data Accessed')], db_index=True, max_length=30)),
                ('resource', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(default=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_logs__action_67259a_idx'), models.Index(fields=['resource', 'resource_id'], name='audit_logs__resourc_8426b3_idx')],
            },
        ),
    ]
