# Generated by Django 5.1.15 on 2026-09-22 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('RESIGNATION_SUBMITTED', 'Resignation Submitted'), ('MANAGER_APPROVAL', 'Manager Approval'), ('ASSET_RETURN', 'Asset Return'), ('ACCESS_REVOCATION', 'Access Revocation'), ('FINAL_PAYROLL', 'Final Payroll Clearance'), ('EXIT_INTERVIEW', 'Exit Interview'), ('DEACTIVATED', 'Employee Deactivated')], default='RESIGNATION_SUBMITTED', max_length=30)),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('assets_returned', models.BooleanField(default=False)),
                ('access_revoked', models.BooleanField(default=False)),
                ('exit_interview_completed', models.BooleanField(default=False)),
                ('exit_interview_notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_workflow', to='employees.employee')),
            ],
        ),
    ]
