# Generated by Django 5.1.15 on 2026-09-22 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('OFFER_ACCEPTED', 'Offer Accepted'), ('DOCUMENT_COLLECTION', 'Document Collection'), ('ACCOUNT_CREATION', 'Account Creation'), ('DEPARTMENT_ASSIGNMENT', 'Department Assignment'), ('EQUIPMENT_ASSIGNMENT', 'Equipment Assignment'), ('TRAINING', 'Training & Orientation'), ('COMPLETED', 'Onboarding Completed')], default='OFFER_ACCEPTED', max_length=30)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('equipment_assigned', models.BooleanField(default=False)),
                ('training_completed', models.BooleanField(default=False)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_workflow', to='employees.employee')),
            ],
        ),
    ]
