# Generated by Django 5.1.15 on 2026-09-22 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, help_text='House Rent Allowance', max_digits=12)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='Provident Fund Deduction', max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='TDS / Income Tax', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_month', models.IntegerField(help_text='Month 1 to 12')),
                ('pay_period_year', models.IntegerField(help_text='Year e.g. 2026')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'ordering': ['-pay_period_year', '-pay_period_month'],
                'unique_together': {('employee', 'pay_period_month', 'pay_period_year')},
            },
        ),
    ]
